= Constructed Inventory Plugin

In this blog post we will look at how we can easily enrich an existing dynamic inventory using the constructed inventory plugin. But, before we do that, let's take a step back.

Ansible is simple automation tool that allows users to achieve common use cases such as configuration management, provisioning and complex multi-tier orchestration. Part of what makes Ansible so simple, is the fact that it is agentless. One doesn't need to deploy agents or any heavyweight control software to get up and running with Ansible automation. So, if Ansible is agentless, how does it know what nodes it should manage? We use an https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html#inventory-basics-formats-hosts-and-groups[inventory] in Ansible to provide it with this list of managed nodes. 

In it's simplest form, an inventory is just an INI or YAML file which contains a list of our managed nodes. This is ideal when getting started with Ansible, but as you start to really use Ansible in anger and at scale you will probably face a couple of questions.

* How do I classify my infrastructure so that I can be more selective in what devices I automate against?

* How do I effectively and efficiently maintain a list of all of my managed nodes?

The answer to both of these questions, can quite often be to use a https://docs.ansible.com/ansible/latest/user_guide/intro_dynamic_inventory.html[dynamic inventory]. A dynamic inventory is a script or plugin which will go to a source of truth and dynamically discover the nodes I need to manage. It will also automatically classify the nodes by putting them into groups which can be used to more selectively target devices when automating with Ansible. There are a number of sources that Ansible can talk to out of the box such as VMware vCenter, AWS, GCP, Azure or Red Hat Satellite (Foreman upstream). There are also community inventory scripts such this the https://github.com/ServiceNowITOM/ansible-sn-inventory[ServiceNow CMDB] script.  And finally, you can https://docs.ansible.com/ansible/latest/dev_guide/developing_inventory.html[develop your own] dyanmic inventory. The benefit to me as a user of Ansible is quite clear. I now no longer need to maintain a list of managed nodes. As I add or remove managed nodes, the dynamic inventory will continue to provide me with an up to date list.

But the dynamic inventory scripts and plugins also provide us with another benefit. They provide rich information about our managed nodes and the environment they are running in. This information is made available to us in the form of variables which we can use in our automation. For example, if we use the AWS (EC2) inventory plugin, then we will retrieve variables for each discovered device such as private IP addresses, regions, security groups and so on. 

=== Dynamic Inventory Example

Let's look at an example of a dynamic inventory script to see what type of information it returns. I'm going to look at the Red Hat Satellite inventory script. https://www.redhat.com/en/technologies/management/satellite[Red Hat Satellite] is a tool that is often used for managing RHEL content and patching of RHEL servers. The script is actually called foreman.py because foreman is one of the upstream components in Red Hat Satellite. 

Here we can see a snippet of the information that is returned by my Satellite server to automatically group my hosts. So for example, we can see a group called foreman_hostgroup_prod_web which contains two hosts - prod-web1.demolab.local and prod-web2.demolab.local. 

[source]
....
ansible-inventory -i foreman.py --graph

@all:
  |--@foreman_content_view_rhel7:
  |  |--dev-web1.demolab.local
  |  |--lb.demolab.local
  |  |--prod-web1.demolab.local
  |  |--prod-web2.demolab.local
  |--@foreman_hostgroup_dev_web:
  |  |--dev-web1.demolab.local
  |--@foreman_hostgroup_prod_haproxy:
  |  |--lb.demolab.local
  |--@foreman_hostgroup_prod_web:
  |  |--prod-web1.demolab.local
  |  |--prod-web2.demolab.local
....

As well as the groupings, we also get a number of facts from Satellite. Again, here is a snippet from one of the hosts:

[source]
....
ansible-inventory -i foreman.py --host prod-web1.demolab.local

{
    "foreman": {
        "subscription_facet_attributes": {
            "autoheal": true, 
            "id": 4883, 
            "last_checkin": "2020-01-14 02:08:23 UTC", 
            "purpose_addons": [], 
            "purpose_role": null, 
            "purpose_usage": null, 
            "registered_at": "2019-12-10 10:21:03 UTC", 
            "registered_through": "sat6.demolab.local", 
            "release_version": null, 
            "service_level": "", 
            "user": null, 
            "uuid": "3a9c2c19-57e4-4f98-b675-99d50d2d5b1e"
        }, 
        "subscription_global_status": 0, 
        "subscription_status": 0, 
        "subscription_status_label": "Fully entitled", 

....

This is just a fraction of the information we get from the inventory source, but we can see lot's of useful information here about the subscription status of this host. These facts are actually host_vars which we can use in our automation.

=== How can we "construct" additional data

So far we have been talking about pretty standard stuff with regards inventories. We've seen the type of facts and groups we get back from the foreman.py inventory script. But what if we want to dynamically create more groups based on the facts that we are getting back? Of course, if you have the necessary skills then you can modify the inventory script to return the information that you need. But, you may not need to do that. There is a really useful inventory plugin which serves this purpose. The https://docs.ansible.com/ansible/latest/plugins/inventory/constructed.html[constructed] inventory plugin takes information from another inventory source and uses that to construct new groups and variables. I really like this because it allows us to keep Ansible simple and avoid writing code if we don't want to.

Let's use our foreman example above to construct a new group. Let's say I want to group hosts based on the Satellite node they are registred through. This would potentially allow me to identify which datacenter or network zone they are in which could be useful if I need to use a jump host to allow Ansible to manage them. Looking at the output above, we can see that this information sits under *foreman.subscription_facet_attributes.registered_through*

=== Example setup

We need a directory for our foreman inventory script and plugin to live in so that we can source the whole directory. I've got my ini file in this directory as well for this example.

[source]
....
inventories/
├── foreman_constructed.yml
├── foreman.ini
└── foreman.py
....

*NOTE* the constructed inventory plugin relies on data from another inventory  source so we need the foreman.py script to run before the constructed inventory. When sourcing a directory as an Ansible inventory they are executed alphabetically. More information can be found https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html#using-multiple-inventory-sources[here]

Here are the contents of my foreman_constructed.yml file.

[source]
....
plugin: constructed
strict: False
keyed_groups:
  -  prefix: ""
     separator: ""
     key: foreman.subscription_facet_attributes.registered_through
....

We should now see an additional group when using these inventory sources.

[source]
....
ansible-inventory -i inventories/ --list

    "sat6_demolab_local": {
        "hosts": [
            "dev-web1.demolab.local", 
            "lb.demolab.local", 
            "prod-web1.demolab.local", 
            "prod-web2.demolab.local"
....

We can now see a group called sat6_demolab_local (underscore has replaced the fullstops) which it has constructed from the facts obtained by foreman inventory script.

=== Using this in Tower





