= Constructed Inventory Plugin

In this blog post we will look at how we can easily enrich an existing dynamic inventory using the constructed inventory plugin. But, before we do that, let's take a step back.

Ansible is simple automation tool that allows users to achieve common use cases such as configuration management, provisioning and complex multi-tier orchestration. Part of what makes Ansible so simple, is the fact that it is agentless. One doesn't need to deploy agents or any heavyweight control software to get up and running with Ansible automation. So, if Ansible is agentless, how does it know what nodes it should manage? We use an https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html#inventory-basics-formats-hosts-and-groups[inventory] in Ansible to provide it with this list of managed nodes. 

In it's simplest form, an inventory is just an INI or YAML file which contains a list of our managed nodes. This is ideal when getting started with Ansible, but as you start to really use Ansible in anger and at scale you will probably face a couple of questions.

* How do I classify my infrastructure so that I can be more selective in what devices I automate against?

* How do I effectively and efficiently maintain a list of all of my managed nodes?

The answer to both of these questions, can quite often be to use a https://docs.ansible.com/ansible/latest/user_guide/intro_dynamic_inventory.html[dynamic inventory]. A dynamic inventory is a script or plugin which will go to a source of truth and dynamically discover the nodes I need to manage. It will also automatically classify the nodes by putting them into groups which can be used to more selectively target devices when automating with Ansible. There are a number of sources that Ansible can talk to out of the box such as VMware vCenter, AWS, GCP, Azure or Red Hat Satellite (Foreman upstream). There are also community inventory scripts such this the https://github.com/ServiceNowITOM/ansible-sn-inventory[ServiceNow CMDB] script.  And finally, you can https://docs.ansible.com/ansible/latest/dev_guide/developing_inventory.html[develop your own] dyanmic inventory. The benefit to me as a user of Ansible is quite clear. I now no longer need to maintain a list of managed nodes. As I add or remove managed nodes, the dynamic inventory will continue to provide me with an up to date list.

But the dynamic inventory scripts and plugins also provide us with another benefit. They provide rich information about our managed nodes and the environment they are running in. This information is made available to us in the form of variables which we can use in our automation. For example, if we use the AWS (EC2) inventory plugin, then we will retrieve variables for each discovered device such as private IP addresses, regions, security groups and so on. 


Let's look at an example of the Satellite dynamic inventory script.



We can use those facts to construct additional groups to meet our automation needs.

Example with foreman to show groups. 

Example facts we get.

Example - I want a group for all servers of type a,b or c.

This allows me to assign variables to these groups as well.



